# Generated by Django 4.2.8 on 2023-12-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
