# Generated by Django 4.2.8 on 2023-12-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categories'),
        ),
    ]
