# Generated by Django 4.2.8 on 2023-12-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_recipes_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='user_id',
            new_name='user',
        ),
    ]
