# Generated by Django 4.2.8 on 2023-12-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ingredients_recipeingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
