# Generated by Django 4.2.8 on 2023-12-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_recipeingredient_quantity'),
        ('app', '0009_ratings'),
    ]

    operations = [
    ]
